In [1]:
class Employee:
    # Class variable to count number of employees
    employee_count = 0
    total_salary = 0

    def __init__(self, name, family, salary, department):
        self.name = name
        self.family = family
        self.salary = salary
        self.department = department
        Employee.employee_count += 1
        Employee.total_salary += salary

    @classmethod
    def average_salary(cls):
        if cls.employee_count > 0:
            return cls.total_salary / cls.employee_count
        else:
            return 0

class FulltimeEmployee(Employee):
    # Inherits everything from Employee
    pass

# Creating an instance of Employee
emp1 = Employee("John", "Doe", 60000, "HR")
emp2 = Employee("Jane", "Doe", 65000, "Finance")

# Creating an instance of FulltimeEmployee
fte1 = FulltimeEmployee("Mike", "Smith", 70000, "Engineering")

# Displaying average salary
print(f"Average Salary: {Employee.average_salary()}")

# Output total number of employees
print(f"Total Employees: {Employee.employee_count}")


Average Salary: 65000.0
Total Employees: 3


In [2]:
import numpy as np

# Create a random vector of size 20 with values in the range 1-20
random_vector = np.random.uniform(low=1.0, high=20.0, size=20)

# Reshape the array to 4x5
reshaped_array = random_vector.reshape(4, 5)

# Replace the max in each row by 0 without using a for loop
reshaped_array[np.arange(4), reshaped_array.argmax(axis=1)] = 0

print(reshaped_array)


[[ 9.60332459 11.5305395   7.50206185  0.          5.94108219]
 [ 0.         17.24680414 11.40562925 17.53918774 12.73032362]
 [ 3.28531225  0.         16.22616182  4.03618262  1.98383304]
 [ 0.         14.08779011  4.48299683  1.90333557  8.46098986]]
